# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-79bfa23f-dd1d-49df-ad76-92b2aeededa6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-79bfa23f-dd1d-49df-ad76-92b2aeededa6".device = "/dev/disk/by-uuid/79bfa23f-dd1d-49df-ad76-92b2aeededa6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BC8E-AF07";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-db0fdca1-1917-48ad-bc80-3b2de1f4480e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
