[colors.primary]
background = '#101417'
foreground = '#dfe3e8'

[colors.selection]
text = '#dfe3e8'
background = '#004c6e'

[colors.cursor]
text = '#101417'
cursor = '#94cdf7'

[colors.normal]
black   = '#101417'
red     = '#ff729e'
green   = '#7bf78a'
yellow  = '#fff772'
blue    = '#79baea'
magenta = '#1e4e72'
cyan    = '#94cdf7'
white   = '#eff8ff'

[colors.bright]
black   = '#949ba0'
red     = '#ff9fbc'
green   = '#a5ffb0'
yellow  = '#fff9a5'
blue    = '#a8daff'
magenta = '#b7e0ff'
cyan    = '#d1ebff'
white   = '#f8fcff'
