# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8d25de02-8904-49e2-8d22-23cbcaa3437c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8d25de02-8904-49e2-8d22-23cbcaa3437c".device = "/dev/disk/by-uuid/8d25de02-8904-49e2-8d22-23cbcaa3437c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3CB5-48F3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-04aba2c5-885f-4ae6-a5ea-80acc78e7e4e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
